- name: Update APT cache and install a package
  hosts: "{{targets}}"
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install the specified package
      apt:
        name: "{{package}}"
        state: present
