- name: Update Debian / Ubuntu Systems
  hosts: "{{targets}}"
  become: yes
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Remove unused packages
      apt:
        autoremove: yes
